# Generated by Django 4.0.6 on 2022-08-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='icategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_icon', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
