# Generated by Django 4.0.6 on 2022-08-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='icategories',
            new_name='categories',
        ),
    ]
